### PR TITLE
Add eslint config

### PR DESCRIPTION
**Pull request by karliky**
Fixes https://github.com/Robot/robot-js/issues/29

**Description:**
This PR adds the eslint configuration to the project. It enables ES6 syntax and supports our current coding style guide.

Npm script to run the linter:
`$ npm run eslint`

I had to solve some minor errors like unused vars, mixed tabs/spaces etc.

You can also integrate the linter in Atom.io or SublimeText by installing the required packages, [this is my current configuration](https://user-images.githubusercontent.com/881069/29348895-0772c4e0-8257-11e7-8bb2-ed52398d0fd2.png).

**Tests:**
I haven't been able to pass all the tests, I executed this command `$ node ./Test/Test.js all` but it always fails under the Keyboard tests.

Here is the stack trace:
```
BEGIN KEYBOARD TESTING
------------------------------
Press enter to begin live test
Numbers: 0123456789
Alphabet: abcdefghijklmnopqrstuvwxyz
Alphabet: ABCDEFGHIJKLMNOPQRSTUVWXYZ
Keypad: +-*/,0123456789
/Users/karliky/Documents/personal/robot-js/Test/Test.js:47
	if (!cond) throw new Error
	           ^

Error: Assertion Failed

    at assert (/Users/karliky/Documents/personal/robot-js/Test/Test.js:47:19)
    at testLive (/Users/karliky/Documents/personal/robot-js/Test/Keyboard.js:565:3)
```
Am I doing something wrong? Is this the correct way to launch the tests? This also happens on the `dev` branch in my computer (Macosx sierra) so it's not related to the eslint changes.

I would like to merge this once tests pass ok.

### CODE REVIEW

**Comment by dkrutsko** [comment]
Yeah those are way too many changes. I actually already have a custom eslint [configuration](https://gist.github.com/dkrutsko/5682b8ec5b25529e2e9794ef9bf18761) to match most of the coding style of the project. I'd rather keep the codebase clean and the linter useful than mess everything up and have the linter get in the way.

I also originally wanted to implement it as part of robot-js 2.0 when we switch to ES6 and drop Node 0.12 support but if you'd really like to get it in for the upcoming release, we'll need to modify a few things, mainly the configuration and include an npm script to check the project.

**Comment by karliky** [comment]
Great! 👍  So we'll work on this in the switch to ES6.

I'm going to close this as there is no need to keep it open.

**Comment by p120ph37** [comment]
As far as the tests, the problem is that Robot is a process and system automation library, so in order to properly test, it needs to interact with the system and other processes.  A couple of the tests, like the Types test can run completely self-contained, but the rest require some manual interaction of the user and/or additional target apps. (in my prebuilt branch, you can see a minimal test script that just runs the self-contained tests and skips the rest)

What I've suggested elsewhere is that we might be able to have electron as a dev-dependency for this package, and launch an electron app to be the target of the automation tasks that the tests will perform.  I haven't actually done any work on this idea yet though.

**Comment by dkrutsko** [comment]
@p120ph37 I was actually thinking about this problem a bit, I'm sure some sort of automated tests can be achieved, either through an electron app running on a desktop or just robot running on a desktop. The question is whether it's really necessary.

Most of what could go wrong is in the compilation process or loading the module, which can be tested via types and timer. While classes like process could fail, it's much more likely that they fail on the robot side. Before each release, I actually manually test everything on three platforms using the latest version of node. The rest, I'll set it up so it automatically tests like your prebuilt branch.

In addition to types and timer, there are test cases in classes like Process that test structures, operators, etc. I'll rewrite them to make them accessible through the command line. Most of that is already done in robot, I'll just bring those changes into robot-js. I believe it'll solve the majority of the problem. Let me know what you guys think!

**Comment by karliky** [comment]
So, Are we talking about a robot-cli? 😄 

For instance:
```
$ robot
$ const proc = attach('wow');
$ proc.sendKeys(ROBOT.ENTER);
```

**Comment by dkrutsko** [comment]
You know @karliky, I gave it some more thought. Would be cool to be able to do something like: `robot-cli mouse move 10 20` or `robot-cli process list`. Not sure about `attach` or anything like that but sounds like a cool idea!

**Pull request closed without merging**
